### ISSUE TITLE
Error on last digit with Seg7x4 display

### ISSUE THREAD

**Issue by g-ollivier** [hybotics/Hybotics_Micropython_HT16K33#1]
Hello,

I'm using the adafruit micropython build on a feather_m0_basic

When using library with Adafruit 7x4 display, I noticed a funny behavior with some integer numbers.
The number is displayed with value-1

Exemples : 
after setting i2c and mydisplay = ht16k33_seg.Seg7x4(i2c)

mydisplay.number(1969) becomes 1968 on the display
mydisplay.number(1236) becomes 1235 on the display

I don't have a solution but I noticed the following things

* In the Seg14x4.number method, there is this conversion  s = "{:f}".format(number)
* "{:f}".format(1969)  gives '1968.999862'
* "{:f}".format(1236)  gives '1235.999941'
and
"{:.0f}".format(1236)  gives '1235'

**Comment by g-ollivier** [comment]
Same result regarding the string-format function with esp8266 and latest build

And "{:f}".format(123.6) returns '123.599970'

It seems linked with https://github.com/micropython/micropython/issues/2616

**Comment by tannewt** [comment]
Most of those seem ok because as the issue you linked to states, floats are only so precise. Without specifying the number of decimal places you want, I wouldn't expect the exact same result back. However, it is weird that "{:.0f}".format(1236) gives '1235'. I would expect it to round.

For the driver, we should be able to autorange so that it picks the most appropriate number of decimal places.

**Comment by g-ollivier** [comment]
I noticed tonight Tony D hits a same bug with the 9999 number in this video https://www.youtube.com/watch?v=0GoAtldfGSU 

I added print debugs in the number function and saw the round problem occur.
Until an updated version of the number function, I will use a simple loop over the 4 digits :)

**Comment by kattni** [comment]
This library is no longer supported. Please see the [CircuitPython library](https://github.com/adafruit/Adafruit_CircuitPython_HT16K33) for using HT16K33 on microcontrollers if you wish to use supported libraries. If you wish to continue development, please fork this repo.
