### ISSUE TITLE
7-Segment examples

### ISSUE THREAD

**Issue by andrhamm** [hybotics/Hybotics_Micropython_HT16K33#5]
I'm having a difficult time getting a 7-Semgent display working on my ESP8266 Feather with MicroPython. I'm building a [nextbus](https://learn.adafruit.com/personalized-esp8266-transit-clock/software) but writing the code myself instead of using the nextbus program from the examples. I have 6 Adafruit HT16K33 backpacks with 0.56" 7-Segment displays, although I can't get even a single example working. There are no installation instructions or usage examples for 7-Segment displays in this repo or anywhere in the Adafruit learning system as far as I can tell. Improvements to the Readme would be much appreciated!

**Comment by ladyada** [comment]
hiya try https://learn.adafruit.com/micropython-hardware-led-backpacks-and-featherwings/micropython

**Comment by andrhamm** [comment]
@ladyada Thanks, but I had been following that tutorial. Unfortunately the instructions don't work, as this repo appears to be broken. The `.mpy` files are not compatible Feather. I see an open PR that seems like it might be related but I assume there is a recompilation process, but there are no instructions and I'm unfamiliar. I also can't find any examples of specifically using the 7-Segment displays (only matrixes) and no mention of how to specify multiple display I2C addresses like the Nextbus project requires.

**Comment by ladyada** [comment]
hiya this sounds more like a tech support issue - please post up in the forums!:)

**Comment by andrhamm** [comment]
It looks like [another user on the forums had the same issues](https://forums.adafruit.com/viewtopic.php?f=47&t=128097&p=642851#p642851). It also looks like the issue may be fixed by merging the PR and doing a new release.

**Comment by ladyada** [comment]
ok try now!

**Comment by andrhamm** [comment]
Thanks, it works now. I assumed I needed `.mpy` files but the `.py` files on master now solved the issue mentioned in the forum post
