### ISSUE TITLE
Exceptions when attempting to import

### ISSUE THREAD

**Issue by luckenbach** [hybotics/Hybotics_Micropython_HT16K33#8]
It appears that a Class Inheritance was missed and caused a super() to throw an TypeError exception I have created PR to correct this but the 16x8 Matrix still appears to not work.

https://github.com/adafruit/micropython-adafruit-ht16k33/pull/7

**Comment by kattni** [comment]
We have merged this PR with the fix for this issue, however, this library is no longer supported. We are only supporting CircuitPython. Please fork this repo if you wish to continue development.
